count now takes -n option to return raw counts (not normalized)

diff --git a/count b/count
--- a/count
+++ b/count
@@ -15,4 +15,16 @@
 #  You should have received a copy of the GNU General Public License
 #  along with Datatools.  If not, see <http://www.gnu.org/licenses/>.
 
-awk ' NF > 0{ counts[$0] = counts[$0] + 1; tot = tot + 1} END { for (word in counts) print word, counts[word]/tot; }' | sort -g
+NORMED=true
+while getopts ":nN" opt; do
+  case $opt in
+    n | N) NORMED=false;;
+    \?)    echo "Invalid option: -$OPTARG" >&2;;
+  esac
+done
+
+if $NORMED; then
+    awk ' NF > 0{ counts[$0] = counts[$0] + 1; tot = tot + 1} END { for (word in counts) print word, counts[word]/tot; }' | sort -g
+else
+    awk ' NF > 0{ counts[$0] = counts[$0] + 1} END { for (word in counts) print word, counts[word]; }' | sort -g
+fi
